set(_CATKIN_CURRENT_PACKAGE "panda_loihi")
set(panda_loihi_VERSION "0.0.0")
set(panda_loihi_MAINTAINER "jaimes <jaimes@todo.todo>")
set(panda_loihi_PACKAGE_FORMAT "2")
set(panda_loihi_BUILD_DEPENDS "geometry_msgs" "message_generation" "rospy" "std_msgs" "panda_loihi_msg")
set(panda_loihi_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy" "std_msgs" "panda_loihi_msg")
set(panda_loihi_BUILDTOOL_DEPENDS "catkin" "catkin")
set(panda_loihi_BUILDTOOL_EXPORT_DEPENDS )
set(panda_loihi_EXEC_DEPENDS "geometry_msgs" "rospy" "std_msgs" "message_generation" "panda_loihi_msg")
set(panda_loihi_RUN_DEPENDS "geometry_msgs" "rospy" "std_msgs" "message_generation" "panda_loihi_msg")
set(panda_loihi_TEST_DEPENDS )
set(panda_loihi_DOC_DEPENDS )
set(panda_loihi_URL_WEBSITE "")
set(panda_loihi_URL_BUGTRACKER "")
set(panda_loihi_URL_REPOSITORY "")
set(panda_loihi_DEPRECATED "")