set(_CATKIN_CURRENT_PACKAGE "panda_loihi_msg")
set(panda_loihi_msg_VERSION "0.0.0")
set(panda_loihi_msg_MAINTAINER "jaimes <jaimes@todo.todo>")
set(panda_loihi_msg_PACKAGE_FORMAT "2")
set(panda_loihi_msg_BUILD_DEPENDS "geometry_msgs" "message_generation" "rospy" "std_msgs" "DetectedObject" "DetectedObjectsStamped")
set(panda_loihi_msg_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy" "std_msgs" "DetectedObject" "DetectedObjectsStamped")
set(panda_loihi_msg_BUILDTOOL_DEPENDS "catkin")
set(panda_loihi_msg_BUILDTOOL_EXPORT_DEPENDS )
set(panda_loihi_msg_EXEC_DEPENDS "geometry_msgs" "rospy" "std_msgs" "message_generation" "message_runtime" "DetectedObject" "DetectedObjectsStamped")
set(panda_loihi_msg_RUN_DEPENDS "geometry_msgs" "rospy" "std_msgs" "message_generation" "message_runtime" "DetectedObject" "DetectedObjectsStamped")
set(panda_loihi_msg_TEST_DEPENDS )
set(panda_loihi_msg_DOC_DEPENDS )
set(panda_loihi_msg_URL_WEBSITE "")
set(panda_loihi_msg_URL_BUGTRACKER "")
set(panda_loihi_msg_URL_REPOSITORY "")
set(panda_loihi_msg_DEPRECATED "")